In [1]:
import sympy
sympy.init_printing(use_latex='mathjax')

u1,u2,F1,k,l = sympy.symbols('u_1,u_2,F_1,k,\lambda')

In [2]:
P = k*u1**2/2 + k*(u2-u1)**2/2 - u1*F1
P

             2               2
         k⋅u₁    k⋅(-u₁ + u₂) 
-F₁⋅u₁ + ───── + ─────────────
           2           2      

In [3]:
P1 = P.subs(u2,1/k)
P1e = P1.expand()
P1e

             2         1 
-F₁⋅u₁ + k⋅u₁  - u₁ + ───
                      2⋅k

In [4]:
DP1 = sympy.diff(P1, u1)
DP1

               ⎛       2⎞
             k⋅⎜2⋅u₁ - ─⎟
               ⎝       k⎠
-F₁ + k⋅u₁ + ────────────
                  2      

In [5]:
u11 = sympy.solve(DP1, u1)
u11

⎡F₁ + 1⎤
⎢──────⎥
⎣ 2⋅k  ⎦

In [6]:
P1e.subs(u1, (F1+1)/(2*k)).expand()

    2            
  F₁     F₁    1 
- ─── - ─── + ───
  4⋅k   2⋅k   4⋅k

In [7]:
DP2 = sympy.diff(P1,u1,2)
DP2

2⋅k

In [8]:
PL = P + l*(u2-1/k)
PL

                                2               2
                 ⎛     1⎞   k⋅u₁    k⋅(-u₁ + u₂) 
-F₁⋅u₁ + \lambda⋅⎜u₂ - ─⎟ + ───── + ─────────────
                 ⎝     k⎠     2           2      

In [9]:
DPL1 = sympy.diff(PL, u1)
DPL2 = sympy.diff(PL, u2)
DPL3 = sympy.diff(PL, l)

In [10]:
DPL1.expand()

-F₁ + 2⋅k⋅u₁ - k⋅u₂

In [11]:
DPL2.expand()

\lambda - k⋅u₁ + k⋅u₂

In [12]:
DPL3

     1
u₂ - ─
     k

In [13]:
PLM = PL.subs(l, k*(u1-u2)).expand()
PLM

                     2          
             2   k⋅u₂           
-F₁⋅u₁ + k⋅u₁  - ───── - u₁ + u₂
                   2            

In [14]:
DPM1 = sympy.diff(PLM, u1).expand()
DPM2 = sympy.diff(PLM, u2).expand()

In [15]:
DPM1

-F₁ + 2⋅k⋅u₁ - 1

In [16]:
DPM2

-k⋅u₂ + 1

In [17]:
sympy.linsolve([DPM1, DPM2], [u1,u2])

⎧⎛F₁ + 1  1⎞⎫
⎨⎜──────, ─⎟⎬
⎩⎝ 2⋅k    k⎠⎭

In [18]:
a = sympy.Symbol(r'\alpha')
PP = (P + a*(u2-1/k)**2/2).expand()
PP

                  2                                              2
         \alpha⋅u₂    \alpha⋅u₂   \alpha       2             k⋅u₂ 
-F₁⋅u₁ + ────────── - ───────── + ────── + k⋅u₁  - k⋅u₁⋅u₂ + ─────
             2            k           2                        2  
                                   2⋅k                            

In [19]:
DPP1 = sympy.diff(PP,u1).expand()
DPP1

-F₁ + 2⋅k⋅u₁ - k⋅u₂

In [20]:
DPP2 = sympy.diff(PP,u2).expand()
DPP2

            \alpha              
\alpha⋅u₂ - ────── - k⋅u₁ + k⋅u₂
              k                 

In [23]:
uP = sympy.linsolve([DPP1,DPP2],[u1,u2])
uP

⎧⎛F₁⋅\alpha + F₁⋅k + \alpha  F₁⋅k + 2⋅\alpha⎞⎫
⎪⎜─────────────────────────, ───────────────⎟⎪
⎨⎜                   2                     2⎟⎬
⎪⎝     2⋅\alpha⋅k + k        2⋅\alpha⋅k + k ⎠⎪
⎩                                            ⎭

In [26]:
solutions, = uP
solutions
U1, U2 = solutions

In [27]:
U1

F₁⋅\alpha + F₁⋅k + \alpha
─────────────────────────
                   2     
     2⋅\alpha⋅k + k      

In [28]:
U2

F₁⋅k + 2⋅\alpha
───────────────
              2
2⋅\alpha⋅k + k 

In [33]:
U1a = U1.subs([(k,1),(F1,3)])
U1a

4⋅\alpha + 3
────────────
2⋅\alpha + 1

In [34]:
U2a = U2.subs([(k,1),(F1,3)])
U2a

2⋅\alpha + 3
────────────
2⋅\alpha + 1

In [52]:
from sympy.utilities.lambdify import lambdify
import numpy as np
f1 = lambdify(a, U1a,'numpy') # returns a numpy-ready function
f2 = lambdify(a, U2a,'numpy')
ax = np.array([10, 10**2, 10**4, 10**6, 10**8, 10**10])
f1a = f1(ax)
f2a = f2(ax)

In [61]:
f1a

array([2.04761905, 2.00497512, 2.00005   , 2.0000005 , 2.        ,
       2.        ])

In [54]:
f2a

array([1.0952381 , 1.00995025, 1.0001    , 1.000001  , 1.00000001,
       1.        ])

In [55]:
(f1a - 2)/2

array([2.38095238e-02, 2.48756219e-03, 2.49987501e-05, 2.49999875e-07,
       2.49999998e-09, 2.50000021e-11])

In [56]:
(f2a - 1)/1

array([9.52380952e-02, 9.95024876e-03, 9.99950003e-05, 9.99999500e-07,
       9.99999994e-09, 1.00000008e-10])

In [62]:
K = sympy.Matrix([[2*k, -k], [-k,k+a]])
K

⎡2⋅k      -k    ⎤
⎢               ⎥
⎣-k   \alpha + k⎦

In [63]:
K1 = K.subs([(k,1), (a, 10)])

In [66]:
K1.condition_number().evalf()

5.87747804630494

In [67]:
K8 = K.subs([(k,1), (a, 10**8)])

In [69]:
K8.condition_number().evalf()

50000000.7500000

In [70]:
K.subs([(k,1), (a, 10**2)]).condition_number().evalf()

50.7613945169613

In [71]:
K.subs([(k,1), (a, 10**4)]).condition_number().evalf()

5000.75011251438

In [72]:
K.subs([(k,1), (a, 10**6)]).condition_number().evalf()

500000.750001125