In [17]:
import numpy as np
K = np.matrix([[1,2,2], [2,4,-1], [2,-1,0]])
e, v = np.linalg.eig(K)
y = v * np.diag(e) * np.linalg.inv(v)

In [18]:
print(e)
print(v)
print(y)

[-2.23606798  2.23606798  5.        ]
[[ 6.32455532e-01 -6.32455532e-01 -4.47213595e-01]
 [-3.16227766e-01  3.16227766e-01 -8.94427191e-01]
 [-7.07106781e-01 -7.07106781e-01 -1.09455434e-16]]
[[ 1.00000000e+00  2.00000000e+00  2.00000000e+00]
 [ 2.00000000e+00  4.00000000e+00 -1.00000000e+00]
 [ 2.00000000e+00 -1.00000000e+00 -2.22044605e-16]]
